//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayingCards.Game.Solitaire {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayingCards.Resources.GameResource", typeof(GameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///
        ///&lt;library xmlns=&quot;http://playingcards.org/solitaire&quot;&gt;
        ///	&lt;game id=&quot;1&quot;&gt;
        ///		&lt;!--Meta data here--&gt;
        ///		&lt;metadata name=&quot;Klondike&quot; win_condition=&quot;fill_foundation&quot;&gt;
        ///			&lt;description&gt;...&lt;/description&gt;
        ///			&lt;deck count=&quot;1&quot; type=&quot;full&quot;/&gt;
        ///		&lt;/metadata&gt;
        ///		&lt;layout&gt;
        ///			&lt;stock id=&quot;auto&quot; pos=&quot;1,1&quot; variant=&quot;base&quot; deal_amount=&quot;3&quot; association=&quot;1&quot;/&gt;
        ///			&lt;waste id=&quot;1&quot; pos=&quot;2,1&quot; shown_amount=&quot;3&quot;/&gt;
        ///			&lt;foundation_set start_id=&quot;auto&quot; build_init=&quot;A&quot; build_gap=&quot;1&quot; build_wrapping=&quot;false&quot;&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SolitaireGameData {
            get {
                return ResourceManager.GetString("SolitaireGameData", resourceCulture);
            }
        }
    }
}
